In [1]:
import gym
import torch
import torch.nn as nn
import pickle
import wandb
import pandas as pd
import warnings
import argparse
import numpy as np
import random
from tqdm import tqdm
from collections import deque
from models.lunar_lander_dqn_architecture import lunar_lander_mlp
from rl_utils.stack_frames import stacked_frames_class
from rl_utils.replay_buffer import memory
from rl_utils.replay_buffer import memory_with_curriculum
from rl_utils.optimization import perform_optimization_step

if torch.cuda.device_count() > 1:
    device = torch.device("cuda:"+gpu if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
else:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

Using device: cuda


In [8]:
env = gym.make('BipedalWalker-v3')
obs = env.reset(seed=43)

In [25]:
obs[0]

array([ 2.7471273e-03,  2.6607242e-06, -3.4697267e-04, -1.6000018e-02,
        9.2234910e-02,  8.0548920e-04,  8.6006725e-01,  7.6285080e-04,
        1.0000000e+00,  3.2617871e-02,  8.0543885e-04,  8.5366613e-01,
       -5.4804940e-04,  1.0000000e+00,  4.4081384e-01,  4.4581994e-01,
        4.6142259e-01,  4.8954999e-01,  5.3410256e-01,  6.0246080e-01,
        7.0914859e-01,  8.8593149e-01,  1.0000000e+00,  1.0000000e+00],
      dtype=float32)

In [4]:
env.observation_space.shape[0]

8

In [10]:
model = lunar_lander_mlp(env, 128, 64).to(device)

In [21]:
# Loading saved model
weights = torch.load("models/trained_models/bright-cloud-72LunarLander-v2.pt")
model.load_state_dict(weights)

<All keys matched successfully>

In [25]:

for i in range(5):
    # USing thee environment with random actions
    env = gym.make('LunarLander-v2', render_mode='human')
    obs = env.reset()[0]
    rewards = []
    done = False
    lengths = []
    reward_accum = 0
    while not done:
        action, _ = model.select_action(env, obs, 0.01, 1, 0.01, 1, device)
        obs, reward, done, _, info  = env.step(action)
        reward_accum += reward
        env.render()
    print(f"Episode reward: {reward_accum}")
    env.close()


libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
/home/mario.cantero/.conda/envs/rl_research/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Episode reward: 194.82545354621797


libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast


KeyboardInterrupt: 

In [26]:
env.close()

In [18]:
env.reset()

(array([-0.00270958,  1.4030491 , -0.27446315, -0.34982306,  0.00314648,
         0.06216995,  0.        ,  0.        ], dtype=float32),
 {})

In [46]:
a, b,c ,d, e = env.step(0)

In [47]:
a

array([ 0.02720795,  1.3891824 ,  0.68803257, -0.28137437, -0.03099762,
       -0.15412304,  0.        ,  0.        ], dtype=float32)

In [8]:
len(rewards)

115

In [16]:
obs

array([-0.9374373 ,  0.16288441, -1.2419778 , -0.06932734,  0.79287654,
       -0.63573176,  0.        ,  1.        ], dtype=float32)

In [9]:
done

True

In [13]:
device = "cpu"
action, eps = model.select_action(env, obs, 0.1, 1, 0.1, 1, device)

In [15]:
action.item()

3